<a href="https://colab.research.google.com/github/zbrze/MOWNIT-python-/blob/master/Mownit_lab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Rozwiązywanie układu równań liniowych metodami rozkładu LU 

Podaj zasadę działania metod opartych o dekompozycję LU. 

#### Zadanie 1
Zaimplementuj metody rozkładu LU:
- Rozkład Crouta 
- Rozkład Doolitla
- Rozkład Choleskyego 

Dla każdej z metod podaj warunki niezbędne aby można ją było zastosować. Sprawdź poprawność działania tych metod. 

Przetestuj wydajność algorytmów dla kilku rozmiarów macierzy (podobnie jak w ćwiczeniu 9). 

#### Zadanie 2 (dla chętnych)

#### Zadanie 3 
Zapoznaj się z funkcją rozwiązywania układów równań liniowych dostarczoną przez bibliotekę numpy/scipy. Porównaj jej wydajność z własnymi implementacjami.  




## Podaj zasadę działania metod opartych o dekompozycję LU

Metody te są oparte na rozkładzie macierzy wejściowej (A) na dwie macierze trójkątne - dolnotrójkątną (L) i górnotrójkątną (U), tak aby prawdą było:
 *A = L * U* 

# Rozkład Crouta
elementy na przekątnej macierzy wejściowej muszą być różne od 0

In [0]:
def LU_Solver(l,u,matrixY):
  n = len(matrixY)
  y = np.zeros(n)
  y[0] = matrixY[0] / l[0, 0]
  for i in range(1, n):
        y[i] = (matrixY[i] - np.dot(l[i,: i],y[: i])) / l[i, i]  

  x = np.zeros(n)
  x[n-1] = y[n-1] / u[n-1, n-1]
  for i in range(2, n+1, 1):
     x[-i] = (y[-i] - np.dot(u[-i, -i:],x[-i:])) / u[-i, -i]
  return x
	

In [0]:
def LU_Crout(matrix):
  n = len(matrix)
  l = np.zeros((n,n))
  u = np.zeros((n,n))
  for i in range(n):
    for j in range(i, n):
      l[j][i] = matrix[j][i]
      for k in range(i):
        l[j][i] -= l[j][k] * u[k][i]
    for j in range(i, n):
      if(i == j):
        u[i][i] = 1
      else:
        u[i][j] = matrix[i][j]
        if(l[i][i] == 0):
          print("wrong data!")
          return;
        for k in range(i):
          u[i][j] -= l[i][k] * u[k][j]
        u[i][j] /= l[i][i] 
  return l, u

       
       

In [151]:
import scipy.linalg as la
import numpy as np

matrix1 = np.array([[1.0 ,2.0 ,2.2, 1.0, 2.0],[1.1 ,12.0 ,21.0, 13.0, 1.2],
		   [1.0 ,20.0 ,4.0, 10.0, 1.0], [2.1, 5.0 ,2.0, 6.0, 10.0],  [1.0 ,11.0 ,3.0, 4.0, 12.0]]).reshape(5, 5) 
print(matrix1)
l, u = LU_Crout(matrix1)
print(l)
print(u)
matrix2 = np.array([1.0 ,2.0 ,2.2, 1.0, 2.0])
LU_Solver(l, u, matrix2)

[[ 1.   2.   2.2  1.   2. ]
 [ 1.1 12.  21.  13.   1.2]
 [ 1.  20.   4.  10.   1. ]
 [ 2.1  5.   2.   6.  10. ]
 [ 1.  11.   3.   4.  12. ]]
[[  1.           0.           0.           0.           0.        ]
 [  1.1          9.8          0.           0.           0.        ]
 [  1.          18.         -32.32653061   0.           0.        ]
 [  2.1          0.8         -4.13673469   4.57386364   0.        ]
 [  1.           9.         -16.26326531  -1.46022727  12.34096618]]
[[ 1.          2.          2.2         1.          2.        ]
 [ 0.          1.          1.89591837  1.21428571 -0.10204082]
 [ 0.          0.          1.          0.39772727 -0.02588384]
 [ 0.          0.          0.          1.          1.26251208]
 [ 0.          0.          0.          0.          1.        ]]


array([ 0.63301834,  0.17983324,  0.11295164, -0.24851584,  0.0036687 ])

# Rozkład Doolitla
metoda nie działa jeśli jakikolwiek element na przekątnej macierzy wejściowej jest równy 0

In [0]:
def LU_Doolitl(matrix):
  n = len(matrix)
  l = np.zeros((n,n))
  u = np.zeros((n,n))
  for i in range(n):
    for j in range(i, n):
      u[i][j] = matrix[i][j]
      for k in range(i):
        u[i][j] -= l[i][k] * u[k][j]
    for j in range(i, n):
      if(i == j):
        l[i][i] = 1
      else:
        l[j][i] = matrix[j][i]
        if(u[i][i] == 0):
          print("wrong data!")
          return
        for k in range(i):
          l[j][i] -= l[j][k] * u[k][i]
        l[j][i] /= u[i][i] 
  return l, u

       


In [153]:
matrix1 = np.array([[1.0 ,2.0 ,2.2, 1.0, 2.0],[1.1 ,12.0 ,21.0, 13.0, 1.2],
		   [1.0 ,20.0 ,4.0, 10.0, 1.0], [2.1, 5.0 ,2.0, 6.0, 10.0],  [1.0 ,11.0 ,3.0, 4.0, 12.0]]).reshape(5, 5) 
print(matrix1)
matrix2 = np.array([1.0 ,2.0 ,2.2, 1.0, 2.0])
print(matrix2)

l, u =LU_Doolitl(matrix1)
print("\nMatrix L:\n",l)
print("\n\nMatrix U:\n",u)

print("\n Solution:\n")
LU_Solver(l, u, matrix2)

[[ 1.   2.   2.2  1.   2. ]
 [ 1.1 12.  21.  13.   1.2]
 [ 1.  20.   4.  10.   1. ]
 [ 2.1  5.   2.   6.  10. ]
 [ 1.  11.   3.   4.  12. ]]
[1.  2.  2.2 1.  2. ]

Matrix L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 1.1         1.          0.          0.          0.        ]
 [ 1.          1.83673469  1.          0.          0.        ]
 [ 2.1         0.08163265  0.12796717  1.          0.        ]
 [ 1.          0.91836735  0.50309343 -0.31925466  1.        ]]


Matrix U:
 [[  1.           2.           2.2          1.           2.        ]
 [  0.           9.8         18.58        11.9         -1.        ]
 [  0.           0.         -32.32653061 -12.85714286   0.83673469]
 [  0.           0.           0.           4.57386364   5.77455808]
 [  0.           0.           0.           0.          12.34096618]]

 Solution:



array([ 0.63301834,  0.17983324,  0.11295164, -0.24851584,  0.0036687 ])

# Rozkład Choleskyego
macierz wejściowa musi być symetryczna i określona dodatnio

In [0]:
import math

def LU_Cholesky(matrix):
  n = len(matrix)
  l = np.zeros((n, n))
  for i in range(n):
    for j in range(i+1):
      if(i == j):
        l[j][j] = matrix[i][j]
        for k in range(j):
          l[j][j] -= pow(l[j][k], 2)
        if(l[j][j] > 0):
          l[j][j] = int(math.sqrt(l[j][j]))
      else:
        if(l[j][j]== 0):
          print("wrong data", j)
          return
        else:
          l[i][j] = matrix[i][j]
          for k in range(j):
            l[i][j] -= l[i][k] * l[j][k]
          l[i][j] /= l[j][j]
  return l




In [155]:
matrix1 = np.array([[1.0 ,1.1 ,2.2],[1.1 ,12.0 ,21.0],
		   [2.2 ,21.0 ,1.0]]).reshape(3, 3) 
print(matrix1)
matrix2 = np.array([1 ,1, 1])
print(matrix2)
l= LU_Cholesky(matrix1)
print(l)
LU_Solver(l, l, matrix2)

[[ 1.   1.1  2.2]
 [ 1.1 12.  21. ]
 [ 2.2 21.   1. ]]
[1 1 1]
[[  1.           0.           0.        ]
 [  1.1          3.           0.        ]
 [  2.2          6.19333333 -42.19737778]]


array([ 1.00000000e+00, -1.11111111e-02, -5.57983335e-04])

# Zadanie 3
Zapoznaj się z funkcją rozwiązywania układów równań liniowych dostarczoną przez bibliotekę numpy/scipy. Porównaj jej wydajność z własnymi implementacjami.

In [156]:
from scipy.linalg import lu_factor, lu_solve
matrix1 = np.array([[1.0 ,2.0 ,2.2, 1.0, 2.0],[1.1 ,12.0 ,21.0, 13.0, 1.2],
		   [1.0 ,20.0 ,4.0, 10.0, 1.0], [2.1, 5.0 ,2.0, 6.0, 10.0],  [1.0 ,11.0 ,3.0, 4.0, 12.0]]).reshape(5, 5) 
print(matrix1)
matrix2 = np.array([1.0 ,2.0 ,2.2, 1.0, 2.0])
print(matrix2)
lu, p = lu_factor(matrix1)
x = lu_solve((lu, p), matrix2)
print(x)

[[ 1.   2.   2.2  1.   2. ]
 [ 1.1 12.  21.  13.   1.2]
 [ 1.  20.   4.  10.   1. ]
 [ 2.1  5.   2.   6.  10. ]
 [ 1.  11.   3.   4.  12. ]]
[1.  2.  2.2 1.  2. ]
[ 0.63301834  0.17983324  0.11295164 -0.24851584  0.0036687 ]


## Pomiary wydajności funkcji rozkładu LU Crouta, Doolitla i lu_solve 
przeprowadziłam je poza nootebookiem, dołączam wyniki w formie wykresu.
Pomiary dla rozkładu Choleskiego przeprowadziłam osobno.
Kod którego użyłam:



```
import time
import random
import copy as cp
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import lu_factor, lu_solve

def LU_Solver(l,u,matrixY):
  n = len(matrixY)
  y = np.zeros(n)
  y[0] = matrixY[0] / l[0, 0]
  for i in range(1, n):
        y[i] = (matrixY[i] - np.dot(l[i,: i],y[: i])) / l[i, i]

  x = np.zeros(n)
  x[n-1] = y[n-1] / u[n-1, n-1]
  for i in range(2, n+1, 1):
     x[-i] = (y[-i] - np.dot(u[-i, -i:],x[-i:])) / u[-i, -i]
  return x

def LU_Crout(matrix):
  n = len(matrix)
  l = np.zeros((n,n))
  u = np.zeros((n,n))
  for i in range(n):
    for j in range(i, n):
      l[j][i] = matrix[j][i]
      for k in range(i):
        l[j][i] -= l[j][k] * u[k][i]
    for j in range(i, n):
      if(i == j):
        u[i][i] = 1
      else:
        u[i][j] = matrix[i][j]
        if(l[i][i] == 0):
          print("wrong data!")
          return;
        for k in range(i):
          u[i][j] -= l[i][k] * u[k][j]
        u[i][j] /= l[i][i]
  return l, u


def LU_Doolitl(matrix):
  n = len(matrix)
  l = np.zeros((n,n))
  u = np.zeros((n,n))
  for i in range(n):
    for j in range(i, n):
      u[i][j] = matrix[i][j]
      for k in range(i):
        u[i][j] -= l[i][k] * u[k][j]
    for j in range(i, n):
      if(i == j):
        l[i][i] = 1
      else:
        l[j][i] = matrix[j][i]
        if(u[i][i] == 0):
          print("wrong data!")
          return
        for k in range(i):
          l[j][i] -= l[j][k] * u[k][i]
        l[j][i] /= u[i][i]
  return l, u


def solve_Doolitl(matrixA, matrixB):
    l, u = LU_Doolitl(matrixA)
    x = LU_Solver(l, u, matrixB)
    return x

def solve_Crout(matrixA, matrixB):
    l, u = LU_Crout(matrixA)
    x = LU_Solver(l, u, matrixB)
    return x

def performanceTests():
    n = random.randint(5, 100)
    matrixA = np.random.rand(n, n)
    matrixB = np.random.rand(n, 1)
    start1 = time.time()
    solve_Crout(cp.deepcopy(matrixA), cp.deepcopy(matrixB))
    stop1 = time.time()
    crout_perf = stop1 - start1
    start2 = time.time()
    solve_Doolitl(cp.deepcopy(matrixA), cp.deepcopy(matrixB))
    stop2 = time.time()
    doolitl_perf = stop2 - start2
    start3 = time.time()
    lu_solve((lu_factor(matrixA)), matrixB)
    stop3 = time.time()
    scipy_perf = stop3 - start3
    return n, crout_perf, doolitl_perf, scipy_perf

if __name__ == '__main__':
    crout = []
    doolitl = []
    scipy = []

    for i in range (0,100):
        n_, c_, d_ , s_= performanceTests()
        crout.append((n_, c_))
        doolitl.append((n_, d_))
        scipy.append((n_, s_))

    crout.sort(key=lambda tup: tup[0])
    crout.sort(key=lambda tup: tup[0])
    crout_x = [x[0] for x in crout]
    crout_y = [x[1] for x in crout]

    doolitl.sort(key=lambda tup: tup[0])
    doolitl.sort(key=lambda tup: tup[0])
    doolitl_x = [x[0] for x in doolitl]
    doolitl_y = [x[1] for x in doolitl]

    scipy.sort(key=lambda tup: tup[0])
    scipy.sort(key=lambda tup: tup[0])
    scipy_x = [x[0] for x in scipy]
    scipy_y = [x[1] for x in scipy]

    plt.plot(crout_x, crout_y, 'ro', label="Crout LU")
    plt.plot(doolitl_x, doolitl_y, 'bo', label="Doolitl LU")
    plt.plot(scipy_x, scipy_y, 'go', label="Scipy LU")
    plt.title("Pomiary wydajności")
    plt.xlabel("Matrix size")
    plt.ylabel("Time")
    plt.legend()
    plt.savefig("wykres3")


```



## Test wydajności rozkładu Choleskiego



```
import time
import random
import copy as cp
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import lu_factor, lu_solve
import math

def LU_Solver(l,u,matrixY):
  n = len(matrixY)
  y = np.zeros(n)
  y[0] = matrixY[0] / l[0, 0]
  for i in range(1, n):
        y[i] = (matrixY[i] - np.dot(l[i,: i],y[: i])) / l[i, i]

  x = np.zeros(n)
  x[n-1] = y[n-1] / u[n-1, n-1]
  for i in range(2, n+1, 1):
     x[-i] = (y[-i] - np.dot(u[-i, -i:],x[-i:])) / u[-i, -i]
  return x

def LU_Cholesky(matrix):
  n = len(matrix)
  l = np.zeros((n, n))
  for i in range(n):
    for j in range(i+1):
      if(i == j):
        l[j][j] = matrix[i][j]
        for k in range(j):
          l[j][j] -= pow(l[j][k], 2)
        if(l[j][j] > 0):
          l[j][j] = int(math.sqrt(l[j][j]))
      else:
        if(l[j][j]== 0):
          print("wrong data")
          return
        else:
          l[i][j] = matrix[i][j]
          for k in range(j):
            l[i][j] -= l[i][k] * l[j][k]
          l[i][j] /= l[j][j]
  return l

def Cholesky_solver(matrixA, matrixB):
    l = LU_Cholesky(matrixA)
    if(l is None):
        return
    x = LU_Solver(l, l, matrixB)
    return x


def performanceTests():
    n = random.randint(5, 100)
    A = np.random.rand(n, n)
    matrixA = np.dot(A, A.transpose())
    matrixB = np.random.rand(n, 1)
    start1 = time.time()
    Cholesky_solver(cp.deepcopy(matrixA), cp.deepcopy(matrixB))
    stop1 = time.time()
    cholesky_perf = stop1 - start1
    start3 = time.time()
    lu_solve((lu_factor(matrixA)), matrixB)
    stop3 = time.time()
    scipy_perf = stop3 - start3
    return n, cholesky_perf, scipy_perf

if __name__ == '__main__':
    cholesky = []
    scipy = []

    for i in range (0,100):
        n_, c_, s_= performanceTests()
        cholesky.append((n_, c_))
        scipy.append((n_, s_))

    cholesky.sort(key=lambda tup: tup[0])
    cholesky.sort(key=lambda tup: tup[0])
    cholesky_x = [x[0] for x in cholesky]
    cholesky_y = [x[1] for x in cholesky]

    scipy.sort(key=lambda tup: tup[0])
    scipy.sort(key=lambda tup: tup[0])
    scipy_x = [x[0] for x in scipy]
    scipy_y = [x[1] for x in scipy]

    plt.plot( cholesky_x, cholesky_y, 'ro', label="Cholesky LU")
    plt.plot(scipy_x, scipy_y, 'go', label="Scipy LU")
    plt.title("Pomiary wydajności")
    plt.xlabel("Matrix size")
    plt.ylabel("Time")
    plt.legend()
    plt.savefig("wykres4")


```

