<a href="https://colab.research.google.com/github/zbrze/MOWNIT-python-/blob/master/MOwNiT_lab_%C4%87w_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Rozwiązywanie układów równań liniowych metodami interacyjnymi 

### Zadanie 1
Zaimplementuj metodę Jacobiego. Podaj warunki jej stosowalności. Wygeneruj co najmniej trzy odpowiednie macierze o różnych wielkościach i sprawdź działanie swojej metody. Zwróć uwagę na zbieżność tej metody. 

### Zadanie 2
Zaimplementuj metodę Gaussa-Seidla i kolejnych nadrelaksacji (successive over-relaxation). Podaj warunki stosowalności tych metod. Przeprowadź badanie działania swoich implementacji analogicznie jak w poprzednim zadaniu. Porównaj zbieżność wszystkich trzech metod. 



# Zadanie 1
Zaimplementuj metodę Jacobiego. Podaj warunki jej stosowalności. Wygeneruj co najmniej trzy odpowiednie macierze o różnych wielkościach i sprawdź działanie swojej metody. Zwróć uwagę na zbieżność tej metody.

### **Twierdzenie o zbieżności metody Jacobiego**

W metodzie Jacobiego warunek dostateczny zbieżności, |B|<1, jest spełniony np. wtedy, gdy macierz A ma dominującą przekątną,




![alt text](http://wazniak.mimuw.edu.pl/images/math/a/5/b/a5baccabbc68a36366a3cfdb604c2c44.png)

macierz D musi być odwracalna - na przekątej macierzy nie mogą znajdować się zera

In [0]:
 import numpy as np

 def Jacobi_method(A, B, max_iter, epsilon):
   D = np.diag(np.diag(A))
   LU = A - D
   X = np.zeros_like(B)
   try:
     D_invert = np.linalg.inv(D)
   except: 
     print("Matrix is not invertible")
     return
   for i in range(max_iter):
     X_new = np.zeros_like(X)
     X_new = np.dot(D_invert,B) - np.dot(D_invert,np.dot(LU, X))
     if np.linalg.norm(X_new - X) < epsilon:
            return X_new
     X = X_new
   return X


In [0]:
def relative_error(val, real_val):
  return abs(val - real_val)/abs(real_val)

In [3]:
import statistics as s
import copy 
matrix1_4 = np.array([[11.0, -2.3, 0.5, 11], [1.0, 42.0, 4.5, 0.6], [-2.0, 7.0, 20.0, 0.3], [-5.0, 1.0, 9.0, 26]]).reshape(4,4)
matrix2_4 = np.array([6.0, 6.0, 2.0, 20.0])
print("A: \n",matrix1_4)
print("B: \n",matrix2_4)
numpy = np.linalg.solve(matrix1_4, matrix2_4)
print("numpy solution:\n ", numpy)
iterations = [5, 10, 40, 100]
print('\033[91m', "\nJacobi method: ")
for i in range(len(iterations)):
  j = Jacobi_method(copy.deepcopy(matrix1_4), copy.deepcopy(matrix2_4), iterations[i], 0.0000000000001)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[11.  -2.3  0.5 11. ]
 [ 1.  42.   4.5  0.6]
 [-2.   7.  20.   0.3]
 [-5.   1.   9.  26. ]]
B: 
 [ 6.  6.  2. 20.]
numpy solution:
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 
Jacobi method: 

  5 iterations: 
  [-0.12904585  0.13379769  0.02937436  0.73365731]
 Median of relative error:    0.04629891305469469

  10 iterations: 
  [-0.15373653  0.13318992  0.02723328  0.72531102]
 Median of relative error:    0.0012603132360158847

  40 iterations: 
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 Median of relative error:    4.952289567524091e-14

  100 iterations: 
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 Median of relative error:    2.2999106685219785e-14


In [4]:
matrix1_6 = np.array([[100.0, -1.0, 2.0, -3.0, 11.0 , 0.9], [1.0, 200.0, -4.0, 5.0, 12.5, -2.9], [-2.0, 4.0, 300.0, -6.0, 16.7, - 41.0], [3.0, -5.0, 6.0, 400.0, 0.9, -21.0],
                    [41.0, -35.0, 6.0, 21.0, 180.9, -1.0], [3.0, -5.0, 6.0, 9.0, 0.9, -2001.0]]).reshape(6, 6)
matrix2_6 = np.array([16.0, -26.0, 12.0, -174.0, 21.0, 89.0])
print("A: \n",matrix1_6)
print("B: \n",matrix2_6)
numpy = np.linalg.solve(matrix1_6, matrix2_6)
print("numpy solution:\n ", numpy)
print('\033[91m',"\nJacobi method: ")
for i in range(len(iterations)):
  j = Jacobi_method(copy.deepcopy(matrix1_6), copy.deepcopy(matrix2_6), iterations[i], 0.0000000000001)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[ 1.000e+02 -1.000e+00  2.000e+00 -3.000e+00  1.100e+01  9.000e-01]
 [ 1.000e+00  2.000e+02 -4.000e+00  5.000e+00  1.250e+01 -2.900e+00]
 [-2.000e+00  4.000e+00  3.000e+02 -6.000e+00  1.670e+01 -4.100e+01]
 [ 3.000e+00 -5.000e+00  6.000e+00  4.000e+02  9.000e-01 -2.100e+01]
 [ 4.100e+01 -3.500e+01  6.000e+00  2.100e+01  1.809e+02 -1.000e+00]
 [ 3.000e+00 -5.000e+00  6.000e+00  9.000e+00  9.000e-01 -2.001e+03]]
B: 
 [  16.  -26.   12. -174.   21.   89.]
numpy solution:
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 
Jacobi method: 

  5 iterations: 
  [ 0.133245   -0.12685425  0.02130297 -0.44056082  0.11153346 -0.04582867]
 Median of relative error:    5.020011114705853e-05

  10 iterations: 
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 Median of relative error:    1.3072842659262236e-09

  40 iterations: 
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 Median of relative error:    7.312725

In [5]:
matrix1_11 = np.array([[1123.0, 3.3, 4.0, 11.0, 123.0, 100.0, -1.0, 2.0, -3.0, 11.0 , 0.9], [15.0, 6800.0, -23.0, 1.0, 11.0, 41.0, -35.0, 6.0, 21.0, 180.9, -1.0], 
                    [-13.0, 12.0, 7198.0, 30.0, -5.0, 3.0, -5.0, 6.0, 9.0, 0.9, -201.0], [-3.3, 9.0, 15.0, 980, 9.9, 100.0, -1.0, 2.0, -3.0, 11.0 , 0.9],
                    [11, 0.3, 4.2, 5.0, 4421.1, 3.0, -5.0, 6.0, 400.0, 0.9, -21.0], [11, 3.0, 4.2, 25.0, 3.0, 3211.0, -85.0, 6.0, 41.0, 0.9, -1.0],
                    [-13.0, 12.0, 8.0, 30.0, -5.0, 3.0, -3225.0, 60.0, -9.0, 0.9, 9.0], [-43.0, 12.0, 7.0, 30.0, -5.0, 3.0, 6.0, 3218.0,  9.0, 0.9, -2.0],
                    [-13.0, 12.0, -8.0, 30.0, -5.0, 3.0, -5.0,  9.0, 6099.0, 0.9, -1.0], [-13.0, 12.0, 71.0, 30.0, -5.0, 3.0, -25.0, 6.0, 0.9, 8819.0, 5.0],
                    [-13.0, 12.0, 7198.0, 30.0, -5.0, 3.0, -5.0, 6.0, 9.0, 0.9, 9801.0]]).reshape(11, 11)
matrix2_11 = np.array([11.0, 43.1, 321.0, 16.0, -26.0, 12.0, -174.0, 16.0, 890.0, 321.0, 998.0])
print("A: \n",matrix1_11)
print("B: \n",matrix2_11)
numpy = np.linalg.solve(matrix1_11, matrix2_11)
print("numpy solution:\n ", numpy)
print('\033[91m', "\nJacobi method: ")
for i in range(len(iterations)):
  j = Jacobi_method(copy.deepcopy(matrix1_11), copy.deepcopy(matrix2_11), iterations[i], 0.0000000000001)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[ 1.1230e+03  3.3000e+00  4.0000e+00  1.1000e+01  1.2300e+02  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.5000e+01  6.8000e+03 -2.3000e+01  1.0000e+00  1.1000e+01  4.1000e+01
  -3.5000e+01  6.0000e+00  2.1000e+01  1.8090e+02 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  7.1980e+03  3.0000e+01 -5.0000e+00  3.0000e+00
  -5.0000e+00  6.0000e+00  9.0000e+00  9.0000e-01 -2.0100e+02]
 [-3.3000e+00  9.0000e+00  1.5000e+01  9.8000e+02  9.9000e+00  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.1000e+01  3.0000e-01  4.2000e+00  5.0000e+00  4.4211e+03  3.0000e+00
  -5.0000e+00  6.0000e+00  4.0000e+02  9.0000e-01 -2.1000e+01]
 [ 1.1000e+01  3.0000e+00  4.2000e+00  2.5000e+01  3.0000e+00  3.2110e+03
  -8.5000e+01  6.0000e+00  4.1000e+01  9.0000e-01 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  8.0000e+00  3.0000e+01 -5.0000e+00  3.0000e+00
  -3.2250e+03  6.0000e+01 -9.0000e+00  9.0000e-01  9.0000e+00]
 [-4.3000e+01  1.2000e+01  7.0000e+0

# Zadanie 2
Zaimplementuj metodę Gaussa-Seidla 

Jeśli macierz  A jest diagonalnie dominująca, to metoda Gaussa--Seidela jest zbieżna dla dowolnego wektora startowego

In [0]:
def Gauss_Seidel(A, B, max_iter, epsilon):
  DL = np.tril(A)
  U = A - DL
  try:
    DL_inv = np.linalg.inv(DL)
  except: 
     print("Matrix is not invertible")
     return
  X = np.zeros_like(B)
  for i in range(max_iter):
    X_new = np.zeros_like(X)
    X_new = np.dot(DL_inv, B - np.dot(U, X))
    if np.linalg.norm(X_new - X) < epsilon:
            return X_new
    X = X_new
  return X

In [7]:
print("A: \n",matrix1_4)
print("B: \n",matrix2_4)
numpy = np.linalg.solve(matrix1_4, matrix2_4)
print("numpy solution:\n ", numpy)
iterations = [5, 10, 40, 100]
print('\033[91m',"\nGauss-Seidel method: ")
for i in range(len(iterations)):
  j = Gauss_Seidel(copy.deepcopy(matrix1_4), copy.deepcopy(matrix2_4), iterations[i], 0.0000000000001)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[11.  -2.3  0.5 11. ]
 [ 1.  42.   4.5  0.6]
 [-2.   7.  20.   0.3]
 [-5.   1.   9.  26. ]]
B: 
 [ 6.  6.  2. 20.]
numpy solution:
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 
Gauss-Seidel method: 

  5 iterations: 
  [-0.15280393  0.13325354  0.02720796  0.72530212]
 Median of relative error:    0.0007177749795263399

  10 iterations: 
  [-0.15316798  0.13323192  0.02717335  0.72524492]
 Median of relative error:    5.271097163613712e-08

  40 iterations: 
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 Median of relative error:    1.2438607204464262e-14

  100 iterations: 
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 Median of relative error:    1.2438607204464262e-14


In [8]:
print("A: \n",matrix1_6)
print("B: \n",matrix2_6)
numpy = np.linalg.solve(matrix1_6, matrix2_6)
print("numpy solution:\n ", numpy)
print('\033[91m',"\nGauss-Seidel method: ")
for i in range(len(iterations)):
  j = Gauss_Seidel(copy.deepcopy(matrix1_6), copy.deepcopy(matrix2_6), iterations[i], 0.0000000000001)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[ 1.000e+02 -1.000e+00  2.000e+00 -3.000e+00  1.100e+01  9.000e-01]
 [ 1.000e+00  2.000e+02 -4.000e+00  5.000e+00  1.250e+01 -2.900e+00]
 [-2.000e+00  4.000e+00  3.000e+02 -6.000e+00  1.670e+01 -4.100e+01]
 [ 3.000e+00 -5.000e+00  6.000e+00  4.000e+02  9.000e-01 -2.100e+01]
 [ 4.100e+01 -3.500e+01  6.000e+00  2.100e+01  1.809e+02 -1.000e+00]
 [ 3.000e+00 -5.000e+00  6.000e+00  9.000e+00  9.000e-01 -2.001e+03]]
B: 
 [  16.  -26.   12. -174.   21.   89.]
numpy solution:
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 
Gauss-Seidel method: 

  5 iterations: 
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 Median of relative error:    3.4278778241656495e-09

  10 iterations: 
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 Median of relative error:    4.369182843591023e-16

  40 iterations: 
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 Median of relative error:    4.

In [9]:
print("A: \n",matrix1_11)
print("B: \n",matrix2_11)
numpy = np.linalg.solve(matrix1_11, matrix2_11)
print("numpy solution:\n ", numpy)
print('\033[91m',"\nGauss-Seidel method: ")
for i in range(len(iterations)):
  j = Gauss_Seidel(copy.deepcopy(matrix1_11), copy.deepcopy(matrix2_11), iterations[i], 0.0000000000001)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[ 1.1230e+03  3.3000e+00  4.0000e+00  1.1000e+01  1.2300e+02  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.5000e+01  6.8000e+03 -2.3000e+01  1.0000e+00  1.1000e+01  4.1000e+01
  -3.5000e+01  6.0000e+00  2.1000e+01  1.8090e+02 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  7.1980e+03  3.0000e+01 -5.0000e+00  3.0000e+00
  -5.0000e+00  6.0000e+00  9.0000e+00  9.0000e-01 -2.0100e+02]
 [-3.3000e+00  9.0000e+00  1.5000e+01  9.8000e+02  9.9000e+00  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.1000e+01  3.0000e-01  4.2000e+00  5.0000e+00  4.4211e+03  3.0000e+00
  -5.0000e+00  6.0000e+00  4.0000e+02  9.0000e-01 -2.1000e+01]
 [ 1.1000e+01  3.0000e+00  4.2000e+00  2.5000e+01  3.0000e+00  3.2110e+03
  -8.5000e+01  6.0000e+00  4.1000e+01  9.0000e-01 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  8.0000e+00  3.0000e+01 -5.0000e+00  3.0000e+00
  -3.2250e+03  6.0000e+01 -9.0000e+00  9.0000e-01  9.0000e+00]
 [-4.3000e+01  1.2000e+01  7.0000e+0

### Zaimplementuj metodę kolejnych nadrelaksacji (successive over-relaxation)

In [0]:
def SOR(A, B, max_iter, epsilon, omega):
  D = np.diag(np.diag(A))
  L = np.tril(A - D)
  U = A - D - L
  try:
    D_inv = np.linalg.inv(D)
  except: 
     print("Matrix is not invertible")
     return
  D_inv_omega = np.dot(D_inv, omega)
  X = np.zeros_like(B)
  for i in range(max_iter):
    X_new = np.zeros_like(X)
    X_new = np.add(np.dot((1- omega), X), np.dot(D_inv_omega, B - np.dot(L, X) - np.dot(U, X)))
    if np.linalg.norm(X_new - X) < epsilon:
            return X_new
    X = X_new
  return X

In [11]:
print("A: \n",matrix1_4)
print("B: \n",matrix2_4)
numpy = np.linalg.solve(matrix1_4, matrix2_4)
print("numpy solution:\n ", numpy)
iterations = [5, 10, 40, 100]
print('\033[91m',"\nSuccessive over-relaxation method: ")
for i in range(len(iterations)):
  j = SOR(copy.deepcopy(matrix1_4), copy.deepcopy(matrix2_4), iterations[i], 0.0000000000001, 1.2)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[11.  -2.3  0.5 11. ]
 [ 1.  42.   4.5  0.6]
 [-2.   7.  20.   0.3]
 [-5.   1.   9.  26. ]]
B: 
 [ 6.  6.  2. 20.]
numpy solution:
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 
Successive over-relaxation method: 

  5 iterations: 
  [-0.22194573  0.12635736  0.04542782  0.76112991]
 Median of relative error:    0.2503167654540145

  10 iterations: 
  [-0.14343998  0.13387672  0.02642028  0.72482282]
 Median of relative error:    0.01627675819969099

  40 iterations: 
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 Median of relative error:    6.798964117701983e-09

  100 iterations: 
  [-0.15316795  0.13323193  0.02717336  0.72524493]
 Median of relative error:    5.6060484578738164e-14


In [12]:
print("A: \n",matrix1_6)
print("B: \n",matrix2_6)
numpy = np.linalg.solve(matrix1_6, matrix2_6)
print("numpy solution:\n ", numpy)
print('\033[91m',"\nSuccessive over-relaxation method: ")
for i in range(len(iterations)):
  j = SOR(copy.deepcopy(matrix1_6), copy.deepcopy(matrix2_6), iterations[i], 0.0000000000001, 1.2)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[ 1.000e+02 -1.000e+00  2.000e+00 -3.000e+00  1.100e+01  9.000e-01]
 [ 1.000e+00  2.000e+02 -4.000e+00  5.000e+00  1.250e+01 -2.900e+00]
 [-2.000e+00  4.000e+00  3.000e+02 -6.000e+00  1.670e+01 -4.100e+01]
 [ 3.000e+00 -5.000e+00  6.000e+00  4.000e+02  9.000e-01 -2.100e+01]
 [ 4.100e+01 -3.500e+01  6.000e+00  2.100e+01  1.809e+02 -1.000e+00]
 [ 3.000e+00 -5.000e+00  6.000e+00  9.000e+00  9.000e-01 -2.001e+03]]
B: 
 [  16.  -26.   12. -174.   21.   89.]
numpy solution:
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 
Successive over-relaxation method: 

  5 iterations: 
  [ 0.13428537 -0.12652197  0.02180192 -0.44056252  0.11289013 -0.04585266]
 Median of relative error:    0.0052867041718578115

  10 iterations: 
  [ 0.13322597 -0.1268649   0.02129332 -0.44056202  0.11152022 -0.04582839]
 Median of relative error:    4.061741355447042e-05

  40 iterations: 
  [ 0.13323294 -0.12686123  0.02129683 -0.4405614   0.11152839 -0.04582853]
 Median of relative

In [13]:
print("A: \n",matrix1_11)
print("B: \n",matrix2_11)
numpy = np.linalg.solve(matrix1_11, matrix2_11)
print("numpy solution:\n ", numpy)
print('\033[91m',"\nSuccessive over-relaxation method: ")
for i in range(len(iterations)):
  j = SOR(copy.deepcopy(matrix1_11), copy.deepcopy(matrix2_11), iterations[i], 0.0000000000001, 1.2)
  print("\n",'\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[ 1.1230e+03  3.3000e+00  4.0000e+00  1.1000e+01  1.2300e+02  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.5000e+01  6.8000e+03 -2.3000e+01  1.0000e+00  1.1000e+01  4.1000e+01
  -3.5000e+01  6.0000e+00  2.1000e+01  1.8090e+02 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  7.1980e+03  3.0000e+01 -5.0000e+00  3.0000e+00
  -5.0000e+00  6.0000e+00  9.0000e+00  9.0000e-01 -2.0100e+02]
 [-3.3000e+00  9.0000e+00  1.5000e+01  9.8000e+02  9.9000e+00  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.1000e+01  3.0000e-01  4.2000e+00  5.0000e+00  4.4211e+03  3.0000e+00
  -5.0000e+00  6.0000e+00  4.0000e+02  9.0000e-01 -2.1000e+01]
 [ 1.1000e+01  3.0000e+00  4.2000e+00  2.5000e+01  3.0000e+00  3.2110e+03
  -8.5000e+01  6.0000e+00  4.1000e+01  9.0000e-01 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  8.0000e+00  3.0000e+01 -5.0000e+00  3.0000e+00
  -3.2250e+03  6.0000e+01 -9.0000e+00  9.0000e-01  9.0000e+00]
 [-4.3000e+01  1.2000e+01  7.0000e+0

### Porównaj zbieżność wszystkich trzech metod.

In [14]:
import statistics as s
print("A: \n",matrix1_11)
print("B: \n",matrix2_11)
numpy = np.linalg.solve(matrix1_11, matrix2_11)
print("numpy solution:\n ", numpy)
for i in range(len(iterations)):
  print('\033[91m',"\nJacobi method: ")
  j = Jacobi_method(copy.deepcopy(matrix1_11), copy.deepcopy(matrix2_11), iterations[i], 0.0000000000001)
  print('\033[94m', iterations[i], "iterations: \n", '\033[0m', j )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

  print('\033[91m',"\nGauss-Seidel method: ")
  g = Gauss_Seidel(copy.deepcopy(matrix1_11), copy.deepcopy(matrix2_11), iterations[i], 0.0000000000001)
  print('\033[94m', iterations[i], "iterations: \n", '\033[0m', g )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(g, numpy)))

  print('\033[91m',"\nSuccessive over-relaxation method: ")
  j = SOR(copy.deepcopy(matrix1_11), copy.deepcopy(matrix2_11), iterations[i], 0.0000000000001, 1.2)
  print('\033[94m', iterations[i], "iterations: \n", '\033[0m', j, )
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

A: 
 [[ 1.1230e+03  3.3000e+00  4.0000e+00  1.1000e+01  1.2300e+02  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.5000e+01  6.8000e+03 -2.3000e+01  1.0000e+00  1.1000e+01  4.1000e+01
  -3.5000e+01  6.0000e+00  2.1000e+01  1.8090e+02 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  7.1980e+03  3.0000e+01 -5.0000e+00  3.0000e+00
  -5.0000e+00  6.0000e+00  9.0000e+00  9.0000e-01 -2.0100e+02]
 [-3.3000e+00  9.0000e+00  1.5000e+01  9.8000e+02  9.9000e+00  1.0000e+02
  -1.0000e+00  2.0000e+00 -3.0000e+00  1.1000e+01  9.0000e-01]
 [ 1.1000e+01  3.0000e-01  4.2000e+00  5.0000e+00  4.4211e+03  3.0000e+00
  -5.0000e+00  6.0000e+00  4.0000e+02  9.0000e-01 -2.1000e+01]
 [ 1.1000e+01  3.0000e+00  4.2000e+00  2.5000e+01  3.0000e+00  3.2110e+03
  -8.5000e+01  6.0000e+00  4.1000e+01  9.0000e-01 -1.0000e+00]
 [-1.3000e+01  1.2000e+01  8.0000e+00  3.0000e+01 -5.0000e+00  3.0000e+00
  -3.2250e+03  6.0000e+01 -9.0000e+00  9.0000e-01  9.0000e+00]
 [-4.3000e+01  1.2000e+01  7.0000e+0

In [16]:
import statistics as s
matrix1_100 = np.random.rand(100, 100) + np.identity(100)*100
matrix2_100 = np.random.rand(100, 1)
#for i in range(len(matrix1_100)): 
#  matrix1_100[i][i] += 100
numpy = np.linalg.solve(matrix1_100, matrix2_100)
for i in range(len(iterations)):
  print("\n\n\n", '\033[94m', iterations[i], "iterations: \n", '\033[0m' )
  print('\033[91m',"\nJacobi method: ")
  j = Jacobi_method(copy.deepcopy(matrix1_100), copy.deepcopy(matrix2_100), iterations[i], 0.0000000000001)
  
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(j, numpy)))

  print('\033[91m',"\nGauss-Seidel method: ")
  g = Gauss_Seidel(copy.deepcopy(matrix1_100), copy.deepcopy(matrix2_100), iterations[i], 0.0000000000001)
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(g, numpy)))

  print('\033[91m',"\nSuccessive over-relaxation method: ")
  k = SOR(copy.deepcopy(matrix1_100), copy.deepcopy(matrix2_100), iterations[i], 0.0000000000001, 1)
  print('\033[90m', "Median of relative error:  ", '\033[0m', s.median(relative_error(k, numpy)))




  5 iterations: 
 
 
Jacobi method: 
 Median of relative error:    [0.02778255]
 
Gauss-Seidel method: 
 Median of relative error:    [2.03471519e-05]
 
Successive over-relaxation method: 
 Median of relative error:    [0.02778255]



  10 iterations: 
 
 
Jacobi method: 
 Median of relative error:    [0.0008091]
 
Gauss-Seidel method: 
 Median of relative error:    [2.74237445e-10]
 
Successive over-relaxation method: 
 Median of relative error:    [0.0008091]



  40 iterations: 
 
 
Jacobi method: 
 Median of relative error:    [4.93859251e-13]
 
Gauss-Seidel method: 
 Median of relative error:    [3.25161432e-14]
 
Successive over-relaxation method: 
 Median of relative error:    [4.93747603e-13]



  100 iterations: 
 
 
Jacobi method: 
 Median of relative error:    [4.93859251e-13]
 
Gauss-Seidel method: 
 Median of relative error:    [3.25161432e-14]
 
Successive over-relaxation method: 
 Median of relative error:    [4.93747603e-13]
