## Rozwiązywanie układów równań liniowych 

#### Zadanie 1 
Zaimplemenuj metodę eliminacji Gaussa bez pivotingu i z pivotingiem dla układu równań o dowolnym rozmiarze. 

#### Zadanie 2
Zademonstruj działanie algorytmu na macierzy o rozmiarze 5 x 5. Zademonstruj w jakiej sytuacji potrzebny jest pivoting i jak działa. 

#### Zadanie 3
Podaj teorytyczną złożoność obliczeniową algorytmu eliminacji Gaussa. Przeprowadź testy wydajności swojego algorytmu sprawdzając jego działanie dla różnych rozmiarów macierzy (testy powinny być wykonane poza środowiskiem jupyter). Aby wygenerować układ równań, wygeneruj wektor rozwiązań i macierz współczynników losując wartości (skorzystaj z funkcji poznanych w Ćwiczeniu 2) i następnie oblicz wektor wyrazów wolnych. 



# Zadanie 1
### Zaimplemenuj metodę eliminacji Gaussa bez pivotingu i z pivotingiem dla układu równań o dowolnym rozmiarze.

In [20]:
import numpy as np
from numpy.linalg import matrix_rank, det

def Gauss_basic(matrixA, matrixB):
  rows = matrixA.shape[0]
  for i in range (0, rows):
    for j in range (i+1, rows):
          quotient = float(matrixA[j][i])/matrixA[i][i]
          for k in range (i, rows):
            matrixA[j][k] -= float(matrixA[i][k]) * quotient
          matrixB[j] = float(matrixB[j]) - quotient * float(matrixB[i])
          matrixA[j][i] = 0
  solution = [0 for i in range(rows)]
  solution[rows - 1] = matrixB[rows- 1] / matrixA[rows - 1][rows - 1]
  for i in range(rows - 2, -1, -1):
        for j in range(i + 1, rows):
           matrixB[i] -= matrixA[i][j] * solution[j]
        solution[i] =  matrixB[i] / matrixA[i][i]
  return matrixA, solution


In [21]:
def Gauss_pivoting(matrixA):
  n = len(matrixA)
  for i in range (n):

        # partial pivoting
        max_row = i #find row with the greatest number in column i
        counter = 1
        while i+counter<n:
            if abs(matrixA[i+counter,i]) > abs(matrixA[i,i]):
                max_row = i+counter
            counter +=1
        
        if i != max_row: #swap rows if max_row is different than i
            matrixA[max_row], matrixA[i] = matrixA[i], matrixA[max_row].copy()
           
        for j in range (i+1, n):
          quotient = float(matrixA[j][i])/matrixA[i][i]
          for k in range (i, n):
            matrixA[j][k] -= float(matrixA[i][k]) * quotient
          matrixA[j][i] = 0
  return matrixA

# Zadanie 2
### Zademonstruj działanie algorytmu na macierzy o rozmiarze 5 x 5. Zademonstruj w jakiej sytuacji potrzebny jest pivoting i jak działa.

dla macierzy której liczba wierszy równa się jej rzędowi działają oba algorytmu

In [74]:
from numpy.linalg import solve
import copy
matrix1 = np.array([[453,  57,  27],
 [969, 504, 180],
 [102, 558, 685],
 [779, 583, 582],
 [799, 183, 581]]).reshape(5, 3) 
matrix2 = np.array([1.0 ,2.0 ,2.2])
z = np.zeros((max(matrix1.shape), max(matrix1.shape)))
z[:matrix1.shape[0],:matrix1.shape[1]] = matrix1
matrix1 = z
print("Matrix coef")
print(matrix1) 
print("Vector column")
print(matrix2)
print("\n\nWith pivoting")
V, x =  np.linalg.eig(matrix1)
# The linearly dependent row vectors 
matrix1_ = matrix1[V == 0,:]
print(matrix1_)
matrix_new
for j in matrix1_:
  for i in range(0, len(matrix1)):
    if(matrix1[i] == j).all():
      print(j, matrix1[i], i)
    else:
      matrix_new = matrix1[i]

matrix1_ = np.vstack([matrix1_, matrix_new])
print("\n\n",matrix1_)
mP1 = Gauss_pivoting(copy.deepcopy(matrix1_))
print("Row echelon form coef")
print(mP1)

Matrix coef
[[453.  57.  27.   0.   0.]
 [969. 504. 180.   0.   0.]
 [102. 558. 685.   0.   0.]
 [779. 583. 582.   0.   0.]
 [799. 183. 581.   0.   0.]]
Vector column
[1.  2.  2.2]


With pivoting
[[453.  57.  27.   0.   0.]
 [969. 504. 180.   0.   0.]]
[453.  57.  27.   0.   0.] [453.  57.  27.   0.   0.] 0
[969. 504. 180.   0.   0.] [969. 504. 180.   0.   0.] 1


 [[453.  57.  27.   0.   0.]
 [969. 504. 180.   0.   0.]
 [799. 183. 581.   0.   0.]]
Row echelon form coef
[[ 799.          183.          581.            0.            0.        ]
 [   0.          282.06382979 -524.61702128    0.            0.        ]
 [   0.            0.         -389.36080827    0.            0.        ]]


In [3]:
import numpy as np
def j_pivot(row):
    for j in range(len(row)):
        if row[j] != 0:
            return j, True
    return 0, False

# returns the linear_combination row_i + t * row_j
def linear_combination(row_i, row_j, t):
    if len(row_i) != len(row_j):
        print('error: row_i and row_j must have the same length')
        exit(1)

    comb = [0] * len(row_i)
    for i in range(len(row_i)):
        comb[i] = row_i[i] + t * row_j[i]
    
    return comb

# returns the index of the first row, starting from top, with the leftmost pivot
def i_row_leftmost_pivot(matrix):
    i_leftmost_pivot, j_leftmost_pivot = 0, len(matrix[0])
    for i in range(len(matrix)):
        row = matrix[i]
        j_pivot_row, pivot_exists = j_pivot(row)
        if j_pivot_row < j_leftmost_pivot and pivot_exists:
            j_leftmost_pivot = j_pivot_row
            i_leftmost_pivot = i
    
    return i_leftmost_pivot



# main part of gaussian elimination algorithm
def elimination(matrix):
    
    i_to_swap = i_row_leftmost_pivot(matrix)
    matrix[0], matrix[i_to_swap] = matrix[i_to_swap], matrix[0]

    j_pivot_first_row, pivot_exists = j_pivot(matrix[0])

    if not pivot_exists:
        print('error: if first row has no pivot, and the first line row is the one with the leftmost pivot, matrix should be a stair matrix')
        exit(1)

    for i in range(1, len(matrix)):
        j_pivot_row_i, pivot_exists = j_pivot(matrix[i])

        if not pivot_exists:
            continue

        if j_pivot_row_i < j_pivot_first_row:
            print('error: first row should have the leftmost pivot')
            exit(1)
        
        if j_pivot_row_i == j_pivot_first_row:
            matrix[i] = linear_combination(matrix[i], matrix[0], -1 * matrix[i][j_pivot_row_i] / matrix[0][j_pivot_first_row])
    
    stair_matrix = [matrix[0]]
    stair_matrix.extend(elimination(matrix[1:]))
    return stair_matrix

# pretty print of the matrix
def print_matrix(matrix):
    for row in matrix:
        for elem in row:
            print('%.2f\t' % elem, end='')
        print()

def main():

    matrix = np.array([[453,  57,  27],
    [969, 504, 180],
    [102, 558, 685],
    [779, 583, 582],
    [799, 183, 581]]).reshape(5, 3) 
    matrix = elimination(matrix)
    print_matrix(matrix)

if __name__ == '__main__':
    main()

453.00	57.00	27.00	
0.00	382.00	122.00	
0.00	0.00	503.00	
0.00	0.00	0.00	
0.00	0.00	0.00	


In [17]:
def ge_bw(matrix):
    rows=len(matrix)
    cols=len(matrix[0])
    if rows!=cols:
        return -1
    for i in range(rows-1,-1,-1):
        if (matrix[i][cols-1]!=0):
            temp=matrix[cols-1]
            matrix[cols-1]=matrix[i]
            matrix[i]=temp
            break
    for k in range(1,rows,1):
        for j in range (rows-k-1,-1,-1):
            temp=float(matrix[j][cols-k])/(matrix[rows-k][cols-k])
            for i in range(cols-k,-1,-1):
                matrix[j][i]=float(matrix[j][i])-temp*matrix[rows-k][i]
    print (matrix)
    return 0




def ge_fw(matrix):
    rows=len(matrix)
    cols=len(matrix[0])
    if rows!=cols:
        return -1
    for i in range(0,rows,1):
        if (matrix[i][0]!=0):
            temp=matrix[0]
            matrix[0]=matrix[i]
            matrix[i]=temp
            break
    for k in range (1,rows,1):
        for j in range (k,rows,1):
            temp=float(matrix[j][k-1])/(matrix[k-1][k-1])
            for i in range(k-1,cols,1):
                matrix[j][i]=float(matrix[j][i])-temp*matrix[k-1][i]
    print (matrix)
    return 0

In [19]:

matrix = np.array([[453,  57,  27],
    [969, 504, 180],
    [102, 558, 685],
    [779, 583, 582],
    [799, 183, 581]]).reshape(5, 3)
ge_bw(matrix)

-1

In [ ]:
matrix1 = np.array([[1.0 ,2.0 ,2.2, 1.0, 2.0],[1.1 ,12.0 ,21.0, 13.0, 1.2],
		   [1.0 ,20.0 ,4.0, 10.0, 1.0], [2.1, 5.0 ,2.0, 6.0, 10.0]]).reshape(4, 5) 
matrix2 = np.array([[1.0 ,2.0 ,2.2, 1.0],[1.1 ,12.0 ,21.0, 13.0],
		   [1.0 ,20.0 ,4.0, 10.0], [2.1, 5.0 ,2.0, 6.0,],  [1.0 ,11.0 ,3.0, 4.0]]).reshape(5, 4) 
for i in range (0,4):
  for j in range (0, 5):
    matrix2[j][i] = matrix1[3 - i][4 - j]
print(matrix2)
print( matrix1)

[[10.   1.   1.2  2. ]
 [ 6.  10.  13.   1. ]
 [ 2.   4.  21.   2.2]
 [ 5.  20.  12.   2. ]
 [ 2.1  1.   1.1  1. ]]
[[ 1.   2.   2.2  1.   2. ]
 [ 1.1 12.  21.  13.   1.2]
 [ 1.  20.   4.  10.   1. ]
 [ 2.1  5.   2.   6.  10. ]]


In [ ]:

def relative_error(val, real_val):
  return abs(val - real_val)/abs(real_val)

In [ ]:
matrix1 = np.array([[0.00000001, 3212, 3885, 84, 1773], 
      [0.123, 0.00000003, 131, 201, 131], 
      [923, 923, 0.000000043, 3130, 231],
      [123, 3135, 1112, 0.000000012, 2352],
      [2125, 15221, 21451, 121, 0.000000042]]).reshape(5, 5) 
matrix2 = np.array([7.0, 3.0, 6.0, 2.0, 1.0])
print(matrix1)
print("\n\nWithout pivoting")
b1,b2 = Gauss_basic(copy.deepcopy(matrix1), copy.deepcopy(matrix2))
print(b2) 
print("\n\nWith pivoting")

a1, a2 = Gauss_pivoting(copy.deepcopy(matrix1), copy.deepcopy(matrix2))
print(a2)
print("\n\nnumpy solution")
num = solve(matrix1, matrix2)
print(num)
print("\nrelative error:\n")
for i in range(0,5):
  print("\nWithout pivoting")
  print(relative_error(b2[i],num[i]))
  print("\nWith pivoting")
  print(relative_error(a2[i],num[i]))

[[1.0000e-08 3.2120e+03 3.8850e+03 8.4000e+01 1.7730e+03]
 [1.2300e-01 3.0000e-08 1.3100e+02 2.0100e+02 1.3100e+02]
 [9.2300e+02 9.2300e+02 4.3000e-08 3.1300e+03 2.3100e+02]
 [1.2300e+02 3.1350e+03 1.1120e+03 1.2000e-08 2.3520e+03]
 [2.1250e+03 1.5221e+04 2.1451e+04 1.2100e+02 4.2000e-08]]


Without pivoting
[0.13304344292919268, -0.04543667677785119, 0.019260966734039747, -0.02726511531358646, 0.04534913690565393]


With pivoting
[0.13304376038565774, -0.045435883591334984, 0.019260667763220784, -0.02726438732699665, 0.045348320569313316]


numpy solution
[ 0.13304376 -0.04543588  0.01926067 -0.02726439  0.04534832]

relative error:


Without pivoting
2.3861056254529236e-06

With pivoting
2.086198972065509e-16

Without pivoting
1.745727063096883e-05

With pivoting
1.5271836608962824e-16

Without pivoting
1.552234962177811e-05

With pivoting
3.602623745557461e-16

Without pivoting
2.6701006740544315e-05

With pivoting
5.09007873214629e-16

Without pivoting
1.8001467978382285e-05

With 

Po przeanalizowaniu powyższego przykładu możemy wywnioskować że pivoting jest dużo dokładniejszy dla macierzy o dużych amplitudach wartości


# Zadanie 3
### Podaj teorytyczną złożoność obliczeniową algorytmu eliminacji Gaussa. Przeprowadź testy wydajności swojego algorytmu sprawdzając jego działanie dla różnych rozmiarów macierzy (testy powinny być wykonane poza środowiskiem jupyter). Aby wygenerować układ równań, wygeneruj wektor rozwiązań i macierz współczynników losując wartości (skorzystaj z funkcji poznanych w Ćwiczeniu 2) i następnie oblicz wektor wyrazów wolnych.

złożoność obliczeniowa algorytmu eliminacji gaussa: O(n^3)

In [ ]:
import time
import random
import copy as cp
import matplotlib.pyplot as plt
import numpy as np

def Gauss_basic(matrixA, matrixB):
  rows = matrixA.shape[0]
  for i in range (0, rows):
    for j in range (i+1, rows):
          quotient = float(matrixA[j][i])/matrixA[i][i]
          for k in range (i, rows):
            matrixA[j][k] -= float(matrixA[i][k]) * quotient
          matrixB[j] = float(matrixB[j]) - quotient * float(matrixB[i])
          matrixA[j][i] = 0
  solution = [0 for i in range(rows)]
  solution[rows - 1] = matrixB[rows- 1] / matrixA[rows - 1][rows - 1]
  for i in range(rows - 2, -1, -1):
        for j in range(i + 1, rows):
           matrixB[i] -= matrixA[i][j] * solution[j]
        solution[i] =  matrixB[i] / matrixA[i][i]
  return matrixA, solution


def Gauss_pivoting(matrixA, matrixB):
    n = len(matrixA)
    for i in range(n):
        max_row = i 
        counter = 1
        while i + counter < n:
            if abs(matrixA[i + counter, i]) > abs(matrixA[i, i]):
                max_row = i + counter
            counter += 1

        if i != max_row: 
            matrixA[max_row], matrixA[i] = matrixA[i], matrixA[max_row].copy()
            matrixB[max_row], matrixB[i] = matrixB[i], matrixB[max_row].copy()
        for j in range(i + 1, n):
            quotient = float(matrixA[j][i]) / matrixA[i][i]
            for k in range(i, n):
                matrixA[j][k] -= float(matrixA[i][k]) * quotient
            matrixB[j] = float(matrixB[j]) - quotient * float(matrixB[i])
            matrixA[j][i] = 0
    solution = [0 for i in range(n)]
    solution[n - 1] = matrixB[n - 1] / matrixA[n - 1][n - 1]
    for i in range(n - 2, -1, -1):
        for j in range(i + 1, n):
            matrixB[i] -= matrixA[i][j] * solution[j]
        solution[i] = matrixB[i] / matrixA[i][i]
    return matrixA, solution


def performanceTests():
    n = random.randint(5, 100)
    matrixA = np.random.rand(n, n)
    matrixB = np.random.rand(n, 1)

    start1 = time.time()
    Gauss_basic(cp.deepcopy(matrixA), cp.deepcopy(matrixB))
    stop1 = time.time()
    basic_perf = stop1 - start1

    start2 = time.time()
    Gauss_pivoting(cp.deepcopy(matrixA), cp.deepcopy(matrixB))
    stop2 = time.time()
    pivot_perf = stop2 - start2

    return n, basic_perf, pivot_perf

if __name__ == '__main__':

    pivot = []
    basic = []

    for i in range (0,500):
        n_, b_, p_ = performanceTests()
        pivot.append((n_, p_))
        basic.append((n_, b_))

    pivot.sort(key=lambda tup: tup[0])
    basic.sort(key=lambda tup: tup[0])
    pivot_x = [x[0] for x in pivot]
    pivot_y = [x[1] for x in pivot]
    plt.title("Pomiary wydajności dla algorytmu z pivotingiem")
    plt.xlabel("Matrix size")
    plt.ylabel("Time")
    plt.scatter(pivot_x, pivot_y, 'bo')
    plt.savefig("wykres1")


    basic.sort(key=lambda tup: tup[0])
    basic.sort(key=lambda tup: tup[0])
    basic_x = [x[0] for x in basic]
    basic_y = [x[1] for x in basic]
    plt.title("Pomiary wydajności dla algorytmu bez pivotingu")
    plt.xlabel("Matrix size")
    plt.ylabel("Time")
    plt.scatter(basic_x, basic_y, 'or')
    plt.savefig("wykres2")

    plt.scatter(basic_x, basic_y, 'ro', label="without pivoting")
    plt.scatter(pivot_x, pivot_y, 'bo', label="pivoting")
    plt.title("Pomiary wydajności")
    plt.xlabel("Matrix size")
    plt.ylabel("Time")
    plt.plot(basic_x, basic_y, 'or')
    plt.legend()
    plt.savefig("wykres3")