## Algebra liniowa - biblioteki numeryczne 
W środowisku języka Python dostępne są dwie biblioteki numeryczne numpy i scipy. Dokumentacja: https://numpy.org/doc/, https://docs.scipy.org/doc/. Znajdź informacje wyjaśniające różnice między tymi bibliotekami. 

### Zadanie 1
Napisz krótki program, który wyświetli informację o wersji biblioteki oraz jej konfiguracji. Zwróć uwagę z jakich bibliotek numerycznych korzystają biblioteki Python'a

In [0]:
import numpy as np
print("wersja biblioteki:", np.__version__)
print()
print()
print(np.show_config())


wersja biblioteki: 1.18.2


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [0]:
import scipy as scp
print("wersja biblioteki:",scp.__version__)
print()
print()
print(scp.show_config())

wersja biblioteki: 1.4.1


lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


### Zadanie 2 
Napisz program, który wyświetla wbudowaną pomoc dla funkcji: dodawanie wektorów, 

In [0]:
import numpy as np
np.lookfor('adding vectors')
print()
help(np.broadcast)


Search results for 'adding vectors'
-----------------------------------
numpy.broadcast
    Produce an object that mimics broadcasting.

Help on class broadcast in module numpy:

class broadcast(builtins.object)
 |  Produce an object that mimics broadcasting.
 |  
 |  Parameters
 |  ----------
 |  in1, in2, ... : array_like
 |      Input parameters.
 |  
 |  Returns
 |  -------
 |  b : broadcast object
 |      Broadcast the input parameters against one another, and
 |      return an object that encapsulates the result.
 |      Amongst others, it has ``shape`` and ``nd`` properties, and
 |      may be used as an iterator.
 |  
 |  See Also
 |  --------
 |  broadcast_arrays
 |  broadcast_to
 |  
 |  Examples
 |  --------
 |  
 |  Manually adding two vectors, using broadcasting:
 |  
 |  >>> x = np.array([[1], [2], [3]])
 |  >>> y = np.array([4, 5, 6])
 |  >>> b = np.broadcast(x, y)
 |  
 |  >>> out = np.empty(b.shape)
 |  >>> out.flat = [u+v for (u,v) in b]
 |  >>> out
 |  array([[5.,  6

### Zadanie 3
Napisz programy, które testują wektory danych pod kątem obecności elementów zerowych lub nieskończonych (sprawdź różne warianty takich funkcji). 
Napisz program porównujące wektory i macierze (według wartości elementów).

In [0]:
import numpy as np
vector1 =  [float(i) for i in input().split()]
print("Zero elements")
print ("Orginal vector: ", vector1) 
print()
print("Using flatnonzero()")
print ("Index of non zero elements :\n", np.flatnonzero(vector1) )
print()
print("using count_nonzero()")
print("number of non zero elements :\n", np.count_nonzero(vector1))
print()
print("using all()")
print("check if every value in vector is zero : \n",np.all(vector1==0))
print()
print("using any()")
print("check if there is any non zero value in vector :\n",np.any(vector1))
print("---------------------------------------------")
print()
print("Infinite elements")
print()

vector2 = [np.inf, 8, 0, 9, np.inf]
print("orginal vector2: \n", vector2)
print("\nUsing np.isfinite()")
print("Is Finite : \n", np.isfinite(vector2))
print("\nUsing np.asarray_chkfinite()")
print("If there are infinite values in vector the error will occur \n")
print(np.asarray_chkfinite(vector2))


1 2 2 0 9 8 0 0
Zero elements
Orginal vector:  [1.0, 2.0, 2.0, 0.0, 9.0, 8.0, 0.0, 0.0]

Using flatnonzero()
Index of non zero elements :
 [0 1 2 4 5]

using count_nonzero()
number of non zero elements :
 5

using all()
check if every value in vector is zero : 
 False

using any()
check if there is any non zero value in vector :
 True
---------------------------------------------

Infinite elements

orginal vector2: 
 [inf, 8, 0, 9, inf]

Using np.isfinite()
Is Finite : 
 [False  True  True  True False]

Using np.asarray_chkfinite()
If there are infinite values in vector the error will occur 



ValueError: ignored

In [0]:
#napisz program porównujące wektory
import numpy as np
print("first vector")
vector1 = [float(i) for i in input().split()]
print(vector1)
print("second vector")
vector2 = [float(i) for i in input().split()]
print(vector2)
print("Are the vectors equal?:")
np.array_equal(vector1, vector2)


first vector
1 1 2 4
[1.0, 1.0, 2.0, 4.0]
second vector
2 2 1 2
[2.0, 2.0, 1.0, 2.0]
Are the vectors equal?:


False

In [0]:
# i macierze
import numpy as np
print("First matrix")
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
print("Enter values") 
values = list(map(float, input().split())) 
matrix1 = np.array(values).reshape(R, C) 
print(matrix1) 
print("First matrix")
R1 = int(input("Enter the number of rows:")) 
C1 = int(input("Enter the number of columns:")) 
print("Enter values") 
values = list(map(float, input().split())) 
matrix2 = np.array(values).reshape(R, C) 
print(matrix2)
print("Are the matrixes equal?:")
np.array_equal(matrix1, matrix2)

First matrix
Enter the number of rows:2
Enter the number of columns:2
Enter values
2 2 2 2
[[2. 2.]
 [2. 2.]]
First matrix
Enter the number of rows:2
Enter the number of columns:2
Enter values
2 2 2 2
[[2. 2.]
 [2. 2.]]
Are the matrixes equal?:


True

### Zadanie 4 
Napisz program, który wylicza ile danych w bajtach zajmuje wektor lub macierz

In [0]:
import numpy as np
print("matrix")
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
print("Enter values") 
values = list(map(float, input().split())) 
matrix = np.array(values).reshape(R, C) 
print(matrix) 
print(bytearray(matrix))
print(len(bytearray(matrix)))
print()
print("vector")
vector = [int(i) for i in input().split()]
print(vector)
print(bytearray(vector))
print(len(bytearray(vector)))

matrix
Enter the number of rows:3
Enter the number of columns:2
Enter values
11 22 12 13 14 15
[[11. 22.]
 [12. 13.]
 [14. 15.]]
bytearray(b'\x00\x00\x00\x00\x00\x00&@\x00\x00\x00\x00\x00\x006@\x00\x00\x00\x00\x00\x00(@\x00\x00\x00\x00\x00\x00*@\x00\x00\x00\x00\x00\x00,@\x00\x00\x00\x00\x00\x00.@')
48

vector
1 1 2 2
[1, 1, 2, 2]
bytearray(b'\x01\x01\x02\x02')
4


### Zadanie 5
Napisz kilka programów, które demonstrują jak można w numpy tworzyć wektory i macierze wypełnione różnymi danymi lub mającymi pewną szczególną postać, np. , danymi losowymi, danymi z podanego zakresy, macierze identyczności, ... 

In [0]:
import numpy as np

print(np.arange(20))
print()

print( np.zeros((4,4)))
print()
print(np.empty((2,3)))
print()
print(np.full((4,2), 3))
print()
print(np.identity(4)) 
print()
print(np.linspace(0, 10, num=10)) 
print()
print(np.indices((4,4))) 
print()
np.random.seed(0)
print(np.random.randint(10, size=6))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 2. 3.]
 [3. 2. 1.]]

[[3 3]
 [3 3]
 [3 3]
 [3 3]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]

[5 0 3 3 7 9]


### Zadania 6
Napisz programy wykonujący podstawowe operacje algebry: dodawanie wektórów, mnożenie wektorów, mnożenia macierzy. Najpierw napisz je w wersji szkolnej, nie zastanawiając się nad jakąkolwiek optymalizacją. Następnie spróbuj zmienić organizację obliczeń tak by uzyskać poprawę wydajności. Na koniec porównaj swoje metody do dedykowanych funkcji z bibliotek NumPy i SciPy. 


In [0]:
import numpy as np
import time           #do mierzenia czasu działania funkcji

def addvectors(vector1, vector2):
  if len(vector1) != len(vector2):
    return
  vector3 = np.empty(len(vector2))
  for i in range (0, len(vector2)):
    vector3[i] = vector2[i] + vector1[i]
  return vector3

def crossproduct(vector1, vector2):
  vector3 = np.empty(len(vector1))
  vector3[0] = vector1[1] * vector2[2] - vector1[2] * vector2[1]; 
  vector3[1] = vector1[2] * vector2[0] - vector1[0] * vector2[2]; 
  vector3[2] = vector1[0] * vector2[1] - vector1[1] * vector2[0]; 
  return vector3;

def multiplymatrix(matrix1, matrix2):
  if(matrix1.shape[1] != matrix2.shape[0]):
    print("niepoprawny rozmiar")
    return
  matrix3 = np.full((matrix1.shape[0], matrix2.shape[1]), 0)
  for i in range (0,  matrix1.shape[0]):
    for j in range (0, matrix2.shape[1] ):
       for k in range (0,matrix1.shape[1]):
         matrix3[i][j] += matrix1[i][k] * matrix2[k][j] 
  return matrix3

print("multiplying matrix \n")
print("First matrix")
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
print("Enter values") 
values = list(map(float, input().split())) 
matrix1 = np.array(values).reshape(R, C) 
print(matrix1) 
print("Second matrix")
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
print("Enter values") 
values = list(map(float, input().split())) 
matrix2 = np.array(values).reshape(R, C) 
print(matrix2)
start = time.time()
print(multiplymatrix(matrix1, matrix2))
end = time.time()
print("My programm performance: ",end - start)
print()
start = time.time()
print(np.matmul(matrix1, matrix2))
end = time.time()
print("Function performance: ",end - start)
print("\n -------------------------------------------------------------------\n")
print("vector1")
vector1 = [int(i) for i in input().split()]
print(vector1)
print("vector2")
vector2 = [int(i) for i in input().split()]
print(vector2)
print("adding vectors: ")
start = time.time()
print(addvectors(vector1, vector2))
end = time.time()
print("My programm performance: ",end - start)
print()
start = time.time()
print(np.add(vector1, vector2))
end = time.time()
print("Function performance: ",end - start)
print("\n\n")
print("cross product: ")
vector1 = [8, 8, 9]
vector2 = [1, 5, 5]
print(vector1)
print(vector2)
start = time.time()
print(crossproduct(vector1, vector2))
end = time.time()
print("My programm performance: ",end - start)
print()
start = time.time()
print(np.cross(vector1, vector2))
end = time.time()
print("Function performance: ",end - start)


multiplying matrix 

First matrix
Enter the number of rows:3
Enter the number of columns:3
Enter values
1 2 3 1 2 3 1 2 3
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
Second matrix
Enter the number of rows:3
Enter the number of columns:3
Enter values
1 0 0 1 0 0 1 1 1
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 1.]]
[[6 3 3]
 [6 3 3]
 [6 3 3]]
My programm performance:  0.00033593177795410156

[[6. 3. 3.]
 [6. 3. 3.]
 [6. 3. 3.]]
Function performance:  0.005074739456176758

 -------------------------------------------------------------------

vector1
1 2 2 3
[1, 2, 2, 3]
vector2
1 2 5 16
[1, 2, 5, 16]
adding vectors: 
[ 2.  4.  7. 19.]
My programm performance:  0.00039839744567871094

[ 2  4  7 19]
Function performance:  0.00016546249389648438



cross product: 
[8, 8, 9]
[1, 5, 5]
[ -5. -31.  32.]
My programm performance:  0.00024318695068359375

[ -5 -31  32]
Function performance:  0.0011680126190185547
